apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook-mysql
  labels:
    app: webook-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webook-mysql
  template:
    metadata:
      name: webook-mysql
      labels:
        app: webook-mysql
    spec:
      containers:
        - name: webook-mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            # 要对应到mysql对应存储的位置
            # 通过mysql配置可以修改这个
            - mountPath: /var/lib/mysql
              # 使用哪一个volume
              name: mysql-storage
          ports:
            - containerPort: 3306
      restartPolicy: Always
      # 声明有多少个volumes
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: webook-mysql-claim
      