apiVersion: v1
# 这里配置的是k8s有哪些volume
kind: PersistentVolume
metadata:
  name: my-local-pv
spec:
  # 这里可以随意取
  storageClassName: yul
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
