apiVersion: v1
kind: Service
metadata:
  name: webook-redis
spec:
  selector:
    app: webook-redis
  ports:
    - protocol: TCP
      # 对外暴露的端口
      port: 11379
      # redis 默认的端口
      targetPort: 6379
      # k8s (集群外访问的)
      nodePort: 30003
  type: NodePort
  