apiVersion: v1
# 这里配置mysql需要社么类型的volume
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-claim
spec:
  # 这里可以随便取
  storageClassName: yul
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi